sonar.projectKey=student-management
sonar.projectName=Student Management System
sonar.projectVersion=0.0.1

# Source encoding
sonar.sourceEncoding=UTF-8

# Coverage
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Tests
sonar.surefire.reportsPath=target/surefire-reports

# Exclusions
sonar.exclusions=**/entities/**,**/config/**

# Code smells and bugs
sonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
